version: "3"
services:
  dsc-status-bot:
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - .:/app
    ports:
      - "5999:5999"
    environment:
      PYTHONUNBUFFERED: 1
      DISCORD_TOKEN: "token_here"
      DISCORD_TARGET_CHANNEL_ID: "channel_id_here"
      SERVER_PORT: "5999"
    restart: always
